spring:
  application:
    name: coupon-system

  datasource:
    url: jdbc:mysql://localhost:3306/coupon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: coupon
    password: coupon
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 250
      minimum-idle: 5
      connection-timeout: 20000

  data:
    redis:
      host: localhost
      port: 6380

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: coupon-issue-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: ERROR
    com.example.couponsystem.facade.CouponFacade: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
